export const FETCH_QUOTES_START = 'FETCH_QUOTES_START';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE';

export const SET_NEXT_QUOTE = 'SET_NEXT_QUOTE';
